name: 'DORA Metrics'
author: 'Sten Otto Johnsen'
description: 'Outputs a set of key metrics as by State of DevOps report'
inputs:
  owner:  # organisation
    description: 'Owner of the repo. Org or user'
    required: false
  repo:  # repository
    description: 'Repository name'
    required: false
outputs:
  deploy_rate: # pull requests merged to main per week
    description: 'Deployment rate'
runs:
  using: 'node16'
  main: 'dist/index.js'
