name: Calculate DORA Metrics

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Checking the dora metrics
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dora metrics
        uses: ./ # Uses an action in the root directory
        id: dora
        with:
          owner: 'stenjo'
          repo: 'dora'

      # Use the output from the `dora` step
      - name: Get the output rate
        run: echo "The deploy rate was ${{ steps.dora.outputs.deploy-rate }}"      # Use the output from the `dora` step
      - name: Get the change failure rate
        run: echo "The change failure rate was ${{ steps.dora.outputs.change-failure-rate }}"

      - name: Get current date
        id: date
        run: |
          echo "date=$(date +'%m-%d')" >> $GITHUB_OUTPUT

      # - name: Run jq
      #   uses: sergeysova/jq-action@v2
      #   id: jq
      #   with:
      #     multiline: true
      #     cmd: 'jq ".values[.values | length] |= . + {\"date\":\"${{ steps.date.outputs.date }}\", \"rate\":${{ steps.dora.outputs.deploy-rate }}}" deployrate-values.json'

      - name: Install jq
        uses: dcarbone/install-jq-action@v1.0.1
 
      - name: Store in json file
        run: |
          jq `.values[.values | length] |= . + {"date":"${{ steps.date.outputs.date }}", "rate":${{ steps.dora.outputs.deploy-rate }}}` deployrate-values.json
          rm deployrate-values.json
          echo ${{ steps.jq.ouputs.value}} >> deployrate-values.json
          ls  -al
          cat deployrate-values.json
 
